on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Copy to .env
        run: cp ./.env.example ./.env

      - name: Copy to default.json
        run: cp ./backend/src/config/default.json.test ./backend/src/config/default.json

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Install Node.js 19.4.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.4.0'

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./backend/src
      
      - name: Fix for JWT
        run: cat ./backend/fix_jwt.txt  >> ./backend/src/node_modules/@types/express/index.d.ts

      - name: Start Yarn server
        working-directory: ./backend/src
        run: nohup yarn start &

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest tests
